import Head from "next/head";
// import "./GSAPComponent.css";
import Hero from "../components/hero";
import Syllabus from "../components/syllabus";

export default function Home() {
  // useEffect(() => {
  //   gsap.registerPlugin(ScrollTrigger);
  //   gsap.to("#boxc", {
  //     x: 450,
  //     scrollTrigger: {
  //       trigger: "#boxc",
  //       start: "top center",
  //       end: "top 100px",
  //       scrub: true,
  //       markers: true,
  //       toggleActions: "restart pause reverse pause",
  //     },
  //     rotation: 360,
  //     // scrub: true,
  //     delay: 0.3,
  //     ease: "none",
  //     duration: 3,
  //     opacity: 1,
  //     backgroundColor: "purple",
  //   });
  // }, []);

  return (
    <div className="bg-[#1E1E1E] text-white">
      <Head>
        <title>Practice GSAP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
        <Syllabus />
      </main>
    </div>
  );
}
